name: Cypress Tests

on: push

env:
  PGURI:

jobs:
  backend:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install backend dependencies
        run: cd backend &&
          npm i &&
          npm run build &&
          node index.js &
        env:
          CYPRESS_PG: ${{ secrets.PG }}

  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Install NPM dependencies, cache them correctly
        # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          build: npm run build
          start: npm run dev
